config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "home#home"
  get '/movies', to: "home#find", as: "find_movies"
  get '/topmovies', to: "home#top_movies", as: "top_movies"
  get '/movie_overview/:id', to: "home#movie_overview", as: "movie_overview"
  get '/movie/:name/:id', to: "home#find_movie_bygenre", as: "find_genre"
  get '/fetch_data', to: "home#fetch_data", as: "fetch_data"
  get '/play_movies', to: "home#movies_player", as: "movies_player"
  get 'embed/movie/:id', to: 'movies#show', as: 'embed_movie'

  get '/test', to: "home#testing"

  get '/tvshows', to: "tvshows#home"
  get '/tvshows_overview/:id', to: "tvshows#tvshows_overview", as: "tvshows_overview"
  get '/tvshows_player/:series_id/:season_number/:episode_number', to: "tvshows#tvplayer", as: "tvplayer"
  get '/find_tvshows/:search', to: "tvshows#find_tvshows", as: "find_tvshows"

  #### RENDER TO JSON
  namespace :api do
    namespace :v1 do
      ## fetch nowplaying movies
      get '/nowplayingmovies', to: "api#nowplayingmovies"

      get '/genre/:id', to: "api#find_movie_bygenre"

      get '/genre_list', to: "api#movie_genre"

      get '/popular', to: "api#popular"

      get '/details/:id', to: "api#movie_details_byid"

      get '/toprated_movies', to: "api#toprated"

      get '/movie_name/:search', to: "api#find"
    end
  end

  namespace :api do
    namespace :v2 do
      get '/tvshows_overview/:id', to: "tvshows_api_#tvshows_overview"
      get '/find_tvshows/:search', to: "tvshows_api_#find_tvshows"
      get '/tvshows', to: "tvshows_api_#home"
      get '/all_series/:search', to: "tvshows_api_#find_data"
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check


  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/api/v1/api_controller.rb
require_relative '../../../api/tmdbapi'
class Api::V1::ApiController < ApplicationController
  API_KEY = 'Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3NTU0NTY0MjA0ODkyMTQwYzY1OWNiOTY4MzlkYjg0YyIsInN1YiI6IjY1YWU5MzNlMjVjZDg1MDBhY2NiMWE4MSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.S9Jt-21GW3iaDr70K4caK37dhdjH7i5pDGa6d5Ez4vs'

  def nowplayingmovies
  tmdb_api = Tmdbapi.new(API_KEY)
  @now_playing_movies = tmdb_api.now_playing_movies
  render json: @now_playing_movies
  end

  def find_movie_bygenre
    @genre_id = params[:id]
    tmdb_api = Tmdbapi.new(API_KEY)
    @genre_data = tmdb_api.movie_bygenre(@genre_id, @genre_name)
    render json: @genre_data
  end

  def movie_genre
    tmdb_api = Tmdbapi.new(API_KEY)
    @genre_list = tmdb_api.fetch_movie_genres
    render json: @genre_list
  end

  def popular
    tmdb_api = Tmdbapi.new(API_KEY)
    @popular_movies = tmdb_api.popular_movies
    render json: @popular_movies
  end

  def movie_details_byid
    @movie_id ||= params[:id]
    tmdb_api = Tmdbapi.new(API_KEY)
    @movie_details = tmdb_api.movie_details(@movie_id)
    render json: @movie_details
  end

  def toprated
    tmdb_api = Tmdbapi.new(API_KEY)
    @toprated_movies = tmdb_api.toprated_movie
    render json: @toprated_movies
  end

  def find
    @search_movie = params[:search]&.gsub(' ', '%20')
    tmdb_api = Tmdbapi.new(API_KEY)
    @data = tmdb_api.find_movies_byname(@search_movie)
    render json: @data
  end

end

app/controllers/api/v2/tvshows_api_controller.rb
require 'uri'
require 'net/http'
require_relative './../../../api/tmdbapi.rb'
class Api::V2::TvshowsApiController < ApplicationController
  API_KEY = 'Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3NTU0NTY0MjA0ODkyMTQwYzY1OWNiOTY4MzlkYjg0YyIsInN1YiI6IjY1YWU5MzNlMjVjZDg1MDBhY2NiMWE4MSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.S9Jt-21GW3iaDr70K4caK37dhdjH7i5pDGa6d5Ez4vs'

  def pop_tvshows
    tmdb_api = Tmdbapi.new(API_KEY)
    @popular_tvshows = tmdb_api.tvshows
    render json: @popular_tvshows
  end

  def tvshows_overview
    @tvshows_id = params[:id]
    tmdb_api = Tmdbapi.new(API_KEY)
    @tvshows_data = tmdb_api.tvshows_details(@tvshows_id)
    render json: @tvshows_data
  end


  def tvplayer
    ser_id = params[:series_id]
    s_num = params[:season_number]
    ep_num = params[:episode_number]
    @player = "https://vidsrc.xyz/embed/tv?tmdb=#{ser_id}&season=#{s_num}&episode=#{ep_num}"
    render plain: @player
  end

  def find_tvshows
    @tvshows_name = params[:search]&.gsub(' ', '%20')
    tmdb_api = Tmdbapi.new(API_KEY)
    @search_tvshows = tmdb_api.search_tvshows(@tvshows_name)
    render json: @search_tvshows
  end

  def find_data
    @alldata = []
    @search_name = params[:search]&.gsub(' ', '%20')
    tmdb_api = Tmdbapi.new(API_KEY)
    @data = tmdb_api.search_byname(@search_name)
    @alldata.concat(@data[:data][:movies]) 
    @alldata.concat(@data[:data][:tv_shows])
    render json: @alldata
  end


  def home
    pop_tvshows
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
require 'uri'
require 'net/http'
require_relative '../api/tmdbapi'
class HomeController < ApplicationController
API_KEY = 'Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3NTU0NTY0MjA0ODkyMTQwYzY1OWNiOTY4MzlkYjg0YyIsInN1YiI6IjY1YWU5MzNlMjVjZDg1MDBhY2NiMWE4MSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.S9Jt-21GW3iaDr70K4caK37dhdjH7i5pDGa6d5Ez4vs'

def testing
end

def find_movie_bygenre
  movie_genre
  @genre_id = params[:id]
  @genre_name = params[:name]
  tmdb_api = Tmdbapi.new(API_KEY)
  @genre_data = tmdb_api.movie_bygenre(@genre_id, @genre_name)
end

def movie_overview
  movie_genre
  @movie_id = params[:id]
  movie_details_byid
  tmdb_api = Tmdbapi.new(API_KEY)
  @movie_data, @movie_key = tmdb_api.movieoverview(@movie_id)
end

def movie_details_byid
  @movie_id ||= params[:id]
  tmdb_api = Tmdbapi.new(API_KEY)
  @movie_details = tmdb_api.movie_details(@movie_id)
end

def movies_player
  tmdb_api = Tmdbapi.new(API_KEY)
  @url = tmdb_api.movie_player(@movie_url)
end


def fetch_data
  tmdb_api = Tmdbapi.new(API_KEY)
  @now_playing_movies = tmdb_api.now_playing_movies

  render json: @now_playing_movies
end


def now_playing
  tmdb_api = Tmdbapi.new(API_KEY)
  @now_playing_movies = tmdb_api.now_playing_movies

end

def popular
  tmdb_api = Tmdbapi.new(API_KEY)
  @popular_movies = tmdb_api.popular_movies
end

def toprated
  tmdb_api = Tmdbapi.new(API_KEY)
  @toprated_movies = tmdb_api.toprated_movie
end

def movie_genre
  movie_details_byid
  tmdb_api = Tmdbapi.new(API_KEY)
  @genre_list = tmdb_api.fetch_movie_genres
end

def home
  movie_genre
  popular
  now_playing
  toprated
end

  def top_movies
    movie_genre
    tmdb_api = Tmdbapi.new(API_KEY)
    @data = tmdb_api.top_movies
  end

  def find
    @alldata = []
    movie_genre
    @search_name = params[:search]&.gsub(' ', '%20')
    tmdb_api = Tmdbapi.new(API_KEY)
    @data = tmdb_api.search_byname(@search_name)
    @alldata.concat(@data[:data][:movies]) 
    @alldata.concat(@data[:data][:tv_shows])
  end
  

end

app/controllers/tvshows_controller.rb
require 'uri'
require 'net/http'
require_relative '../api/tmdbapi'
class TvshowsController < ApplicationController
  API_KEY = 'Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI3NTU0NTY0MjA0ODkyMTQwYzY1OWNiOTY4MzlkYjg0YyIsInN1YiI6IjY1YWU5MzNlMjVjZDg1MDBhY2NiMWE4MSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.S9Jt-21GW3iaDr70K4caK37dhdjH7i5pDGa6d5Ez4vs'

  def pop_tvshows
    tmdb_api = Tmdbapi.new(API_KEY)
    @popular_tvshows = tmdb_api.tvshows
  end

  def tvshows_overview
    @tvshows_id = params[:id]
    tmdb_api = Tmdbapi.new(API_KEY)
    @tvshows_data = tmdb_api.tvshows_details(@tvshows_id)
    render json: @tvshows_data
  end


  def tvplayer
    ser_id = params[:series_id]
    s_num = params[:season_number]
    ep_num = params[:episode_number]
    @player = "https://vidsrc.xyz/embed/tv?tmdb=#{ser_id}&season=#{s_num}&episode=#{ep_num}"
    render plain: @player
  end

  def find_tvshows
    @tvshows_name = params[:search]&.gsub(' ', '%20')
    tmdb_api = Tmdbapi.new(API_KEY)
    @tvshows_data = tmdb_api.search_tvshows(@tvshows_name)
    render json: @tvshows_data
  end


  def home
    pop_tvshows
  end




end

app/helpers/api/v2/tvshows_api_helper.rb
module Api::V2::TvshowsApiHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tvshows_helper.rb
module TvshowsHelper
end

app/views/home/_searchbtn.html.erb
 <div class="button flex items-center justify-center mb-10">
  <div class="grid w-full">
    <div class="mt-10 text-center">
      <h1 class="text-3xl font-bold">Discover Endless Entertainment</h1>
    </div>
    <div class="mt-6 flex justify-center">
      <%= form_tag(find_movies_url, method: :get, class: "flex items-center") do %>
        <%= text_field_tag :search, @search_movie, class: "border rounded-md md:px-6 px-3 md:py-4 py-1 text-black md:w-96", placeholder: "Search for anything..." %>
        <button type="submit" class="bg-blue-500 ml-1 hover:bg-blue-700 text-white font-bold md:py-4 py-1 md:w-14 font-bold px-4 rounded-md">
          <ion-icon name="search-outline"></ion-icon>
        </button>
      <% end %>
    </div>
  </div>
</div>

app/views/home/fetch_data.html.erb
<ul id="movies-list">
  <%= @now_playing_movies%>
</ul>


app/views/home/find.html.erb
<%= render 'header' %>
<%= render 'searchbtn' %>
<div class="mt-5 grid justify-items-center">
  <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 justify-items-center gap-2">
    <% @alldata.each do |movie| %>
      <div class="bg-white shadow-md rounded-md p-4 w-full grid justify-items-center">
        <%= link_to movie_overview_url(id: movie["id"]), class: "block w-44 h-60 rounded-md overflow-hidden" do %>
          <%= image_tag("https://image.tmdb.org/t/p/w500#{movie['poster_path']}", class: "object-cover w-full h-full") %>
        <% end %>
        <div class="">
          <h2 class="text-lg font-bold mt-2"><%= movie['original_title'] %></h2>
          <p class="mt-2 text-gray-600">Popularity <%= movie['popularity'] %></p>
          <p class="mt-2 text-gray-600">Release Date: <%= movie['release_date'] %></p>
          <p class="mt-2 text-gray-600">Type: <%= movie['series_type'] %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/home/find_movie_bygenre.html.erb
<%= render 'header' %>
<%= render 'searchbtn' %>
<div class="mt-5 grid justify-items-center">
  <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 justify-items-center gap-2">
    <% @genre_data.each do |movie| %>
      <div class="bg-white shadow-md rounded-md p-4 w-full grid justify-items-center">
        <%= link_to movie_overview_url(id: movie["id"]), class: "block w-44 h-60 rounded-md overflow-hidden" do %>
          <%= image_tag("https://image.tmdb.org/t/p/w500#{movie['poster_path']}", class: "object-cover w-full h-full") %>
        <% end %>
        <h2 class="text-lg justify-items-start font-bold mt-2"><%= movie['original_title'] %></h2>
        <div class="flex flex-wrap">
          <% @genre_list.each do |genre| %>
            <% if movie['genre_ids'].include?(genre["id"]) %>
              <p class="ml-2"><%= genre["name"] %></p>
            <% end %>
          <% end %>
        </div>
        <p class="mt-2 text-gray-600">Popularity: <%= movie['popularity'] %></p>
        <p class="mt-2 text-gray-600">Release Date: <%= movie['release_date'] %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/home/home.html.erb
<%= render 'header' %>
<%= render 'searchbtn' %>
<% if flash[:error].present? %>
  <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
    <% flash[:error].each do |message| %>
      <p><%= message %></p>
    <% end %>
  </div>
<% end %>
<div class="mt-5 grid justify-items-center w-full">
  <h1 class="text-xl font-bold">Now Playing Movies</h1>
  <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-6 gap-4">
    <% @now_playing_movies.each do |movie| %>
      <div class="bg-white shadow-md rounded-md p-4 w-full grid justify-items-center">
        <%= link_to movie_overview_url(id: movie["id"]), class: "block w-44 h-60 rounded-md overflow-hidden" do %>
          <%= image_tag("https://image.tmdb.org/t/p/w500#{movie['poster_path']}", class: "object-cover w-full h-full") %>
        <% end %>
        <div class="">
          <h2 class="text-lg font-bold mt-2"><%= movie['original_title'] %></h2>
          <p class="mt-2 text-gray-600">Popularity <%= movie['popularity'] %></p>
          <p class="mt-2 text-gray-600">Release Date: <%= movie['release_date'] %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="mt-10 grid justify-items-center">
  <h1 class="text-xl font-bold">Popular Movies</h1>
  <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-4">
    <% @popular_movies.each do |movie| %>
      <div class="bg-white shadow-md rounded-md p-4 w-full grid justify-items-center">
        <%= link_to movie_overview_url(id: movie["id"]), class: "block w-44 h-60 rounded-md overflow-hidden" do %>
          <%= image_tag("https://image.tmdb.org/t/p/w500#{movie['poster_path']}", class: "object-cover w-full h-full") %>
        <% end %>
        <div class="w-[90%]">
          <h2 class="text-lg font-bold mt-2"><%= movie['original_title'] %></h2>
          <p class="mt-2 text-gray-600">Popularity <%= movie['popularity'] %></p>
          <p class="mt-2 text-gray-600">Release Date: <%= movie['release_date'] %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="mt-10 grid justify-items-center">
  <h1 class="text-xl font-bold">Top Rated Movies</h1>
  <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-4">
    <% @toprated_movies.each do |movie| %>
      <div class="bg-white shadow-md rounded-md p-4 w-full grid justify-items-center">
        <%= link_to movie_overview_url(id: movie["id"]), class: "block w-44 h-60 rounded-md overflow-hidden" do %>
          <%= image_tag("https://image.tmdb.org/t/p/w500#{movie['poster_path']}", class: "object-cover w-full h-full") %>
        <% end %>
        <div class="w-[90%]">
          <h2 class="text-lg font-bold mt-2"><%= movie['original_title'] %></h2>
          <p class="mt-2 text-gray-600">Popularity <%= movie['popularity'] %></p>
          <p class="mt-2 text-gray-600">Release Date: <%= movie['release_date'] %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>



app/views/home/testing.html.erb
<h1>HHHHHHWQEQEQ</h1>

app/views/home/top_movies.html.erb
<%= render 'header' %>
<%= render 'searchbtn' %>
<div class="mt-5 grid justify-items-center">
  <h1 class="text-xl font-bold">Top Rated Movies</h1>
  <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 justify-items-center gap-2">
    <% @data.each do |movie| %>
      <div class="bg-white shadow-md rounded-md p-4 w-full grid justify-items-center">
        <%= link_to movie_overview_url(id: movie["id"]), class: "block w-44 h-60 rounded-md overflow-hidden" do %>
          <%= image_tag("https://image.tmdb.org/t/p/w500#{movie['poster_path']}", class: "object-cover w-full h-full") %>
        <% end %>
        <div class="">
          <h2 class="text-lg font-bold mt-2"><%= movie['original_title'] %></h2>
          <p class="mt-2 text-gray-600">Popularity: <%= movie['popularity'] %></p>
          <p class="mt-2 text-gray-600">Release Date: <%= movie['release_date'] %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/home/tvshows_overview.html.erb

<% if @tvshows_data.present? %>
<div class="md:w-1/3">
        <img class="w-80 h-auto rounded-md" src="<%= "https://image.tmdb.org/t/p/w500".concat(@tvshows_data["poster_path"]) %>">
    </div>
  <h1><%= @tvshows_data["original_name"] %></h1>
  <p><%= @tvshows_data["overview"] %></p>
   <% episode_num = @tvshows_data["number_of_episodes"].to_i %>
   <% (1..episode_num).each do |number| %>
    <div class="flex"><p class="bg-yellow-300 p-3 gap-3"><%= number %></p></div>
<% end %>
  <p>Number of seasons: <%= @tvshows_data["number_of_seasons"] %></p>
<% else %>
  <p>No TV show data available.</p>
<% end %>

app/views/layouts/shared/_header.html.erb
   <div class="nav-container bg-black text-white">
        <nav class="flex justify-between items-center w-[90%] mx-auto">
            <div class="logo font-black flex text-3xl">
                <h1>Movie</h1>
                <h1 class="text-[#4FC3F7]">Free</h1>   
            </div>
        <div id="navigationbar" class="md:static md:flex hidden md:min-h-fit md:ml-32 absolute z-10 md:w-auto w-full left-0 top-[8%]">
            <ul class="md:flex-row text-white flex flex-col">
                <li class="p-3 hover:text-[#4FC3F7] text-center bg-[#37474F] rounded-sm border w-full md:w-auto md:bg-transparent md:border-none">
                    <a href="/">Home</a>
                </li>
                <li id="hover-target" class="p-3 hover:text-[#4FC3F7] text-center bg-[#37474F] rounded-sm border w-full md:w-auto md:bg-transparent md:border-none">
                    <a href="">Genre</a>
                </li>
                <li class="p-3 hover:text-[#4FC3F7] text-center bg-[#37474F] rounded-sm border w-full md:w-auto md:bg-transparent md:border-none">
                    <a href=""><%=link_to "Trending Movies", top_movies_path%></a>
                </li>
                <li class="p-3 hover:text-[#4FC3F7] text-center bg-[#37474F] rounded-sm border w-full md:w-auto md:bg-transparent md:border-none">
                    <a href="">Contact Us</a>
                </li>
            </ul>
        </div>
        <div class="icon mr-2 mt-3">
            <ion-icon id="openingnvabar" class="text-3xl md:hidden font-bold" name="menu-outline"></ion-icon>
            <ion-icon id="closingnavbar" class="text-3xl font-bold hidden" name="close-outline"></ion-icon>
        </div>

             <div class="button flex items-center gap-6 hidden md:flex">
                    <button class="bg-[#4FC3F7] p-2 rounded-lg w-[80px]">Login</button>
        </div>
        </nav>
</div>
<div id="hidden-element" class="genres-container hidden w-full flex items-center justify-center bg-gray-300">
  <% @genre_list.each do |genre|%>
  <%= link_to find_genre_url(id: genre["id"], name: genre["name"]) do %>
  <button class="hover:bg-sky-300 p-3 rounded-sm"><%= genre["name"]%></button>
  <%end%>
<%end%>
</div>




<script>
const hoverTarget = document.getElementById('hover-target');
const hiddenElement = document.getElementById('hidden-element');

 hoverTarget.addEventListener('mouseenter', () => {
      hiddenElement.classList.remove('hidden');
    });

    hiddenElement.addEventListener('mouseleave', () => {
      hiddenElement.classList.add('hidden');
    });

     const openingNavbar = document.getElementById('openingnvabar');
    const closingNavbar = document.getElementById('closingnavbar');
    const navigationBar = document.getElementById('navigationbar');

    openingNavbar.addEventListener('click', function() {
        navigationBar.classList.remove('hidden');
        openingNavbar.classList.add('hidden');
        closingNavbar.classList.remove('hidden');
    });

    closingNavbar.addEventListener('click', function() {
        navigationBar.classList.add('hidden');
        openingNavbar.classList.remove('hidden');
        closingNavbar.classList.add('hidden');
    });
</script>

app/views/tvshows/_header.html.erb
   <div class="nav-container bg-black text-white">
        <nav class="flex justify-between items-center w-[90%] mx-auto">
            <div class="logo font-black flex text-3xl">
                <h1>Movie</h1>
                <h1 class="text-[#4FC3F7]">Free</h1>   
            </div>
        <div id="navigationbar" class="md:static md:flex hidden md:min-h-fit md:ml-32 absolute z-10 md:w-auto w-full left-0 top-[8%]">
            <ul class="md:flex-row text-white flex flex-col">
                <li class="p-3 hover:text-[#4FC3F7] text-center bg-[#37474F] rounded-sm border w-full md:w-auto md:bg-transparent md:border-none">
                    <a href="/">Home</a>
                </li>
                <li id="hover-target" class="p-3 hover:text-[#4FC3F7] text-center bg-[#37474F] rounded-sm border w-full md:w-auto md:bg-transparent md:border-none">
                    <a href="">Genre</a>
                </li>
                <li class="p-3 hover:text-[#4FC3F7] text-center bg-[#37474F] rounded-sm border w-full md:w-auto md:bg-transparent md:border-none">
                    <a href=""><%=link_to "Trending Movies", top_movies_path%></a>
                </li>
                <li class="p-3 hover:text-[#4FC3F7] text-center bg-[#37474F] rounded-sm border w-full md:w-auto md:bg-transparent md:border-none">
                    <a href="">Contact Us</a>
                </li>
            </ul>
        </div>
        <div class="icon mr-2 mt-3">
            <ion-icon id="openingnvabar" class="text-3xl md:hidden font-bold" name="menu-outline"></ion-icon>
            <ion-icon id="closingnavbar" class="text-3xl font-bold hidden" name="close-outline"></ion-icon>
        </div>

             <div class="button flex items-center gap-6 hidden md:flex">
                    <button class="bg-[#4FC3F7] p-2 rounded-lg w-[80px]">Login</button>
        </div>
        </nav>
</div>
<div id="hidden-element" class="genres-container hidden w-full flex items-center justify-center bg-gray-300">
  <% @genre_list.each do |genre|%>
  <%= link_to find_genre_url(id: genre["id"], name: genre["name"]) do %>
  <button class="hover:bg-sky-300 p-3 rounded-sm"><%= genre["name"]%></button>
  <%end%>
<%end%>
</div>




<script>
const hoverTarget = document.getElementById('hover-target');
const hiddenElement = document.getElementById('hidden-element');

 hoverTarget.addEventListener('mouseenter', () => {
      hiddenElement.classList.remove('hidden');
    });

    hiddenElement.addEventListener('mouseleave', () => {
      hiddenElement.classList.add('hidden');
    });

     const openingNavbar = document.getElementById('openingnvabar');
    const closingNavbar = document.getElementById('closingnavbar');
    const navigationBar = document.getElementById('navigationbar');

    openingNavbar.addEventListener('click', function() {
        navigationBar.classList.remove('hidden');
        openingNavbar.classList.add('hidden');
        closingNavbar.classList.remove('hidden');
    });

    closingNavbar.addEventListener('click', function() {
        navigationBar.classList.add('hidden');
        openingNavbar.classList.remove('hidden');
        closingNavbar.classList.add('hidden');
    });
</script>

app/views/tvshows/find_tvshows.html.erb
<h1>wqeqwe</h1>
<%=@tvshows_data%>

app/views/tvshows/home.html.erb
<div class="mt-20 grid justify-items-center">
  <h1 class="text-xl font-bold">TV Shows</h1>
  <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-4">
    <% @popular_tvshows.each do |tvshow| %>
      <div class="bg-white shadow-md rounded-md p-4 w-full grid justify-items-center">
        <%= link_to tvshows_overview_url(id: tvshow["id"]), class: "block w-44 h-60 rounded-md overflow-hidden" do %>
          <%= image_tag(tvshow['profile_picture_url'], class: "object-cover w-full h-full") %>
        <% end %>
        <div class="w-[90%]">
          <h2 class="text-lg font-bold mt-2"><%= tvshow['original_name'] %></h2>
          <p class="mt-2 text-gray-600">Popularity <%= tvshow['popularity'] %></p>
          <p class="mt-2 text-gray-600">Release Date: <%= tvshow['release_date'] %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/tvshows/tvplayer.html.erb
<iframe class="w-full h-screen" src="<%=@player%>" frameborder="0"></iframe>

app/views/tvshows/tvshows_overview.html.erb
<%=@tvshows_data%>